### ISSUE TITLE
Choice of HID python library?

### ISSUE THREAD

**Issue by colemickens** [mart1nro/joycontrol#35]
Hi. I'm trying to package this for NixOS users in nixpkgs. However, it looks like I'm going to have to also package `hid`. It has considerably fewer stars/users/releases/etc than `hidapi`.

Did  you choose `hid` for a specific reason?

**Comment by colemickens** [comment]
I also ask because the other library, `hidapi` has had a recent release that I can feel more comfortable packaging.

**Comment by colemickens** [comment]
Ah, `hid` has releases too, they're just not tagged on GitHub.

**Comment by mart1nro** [comment]
Hi, there is no particular reason. It was the first one I found and it worked.

**Comment by colemickens** [comment]
Makes sense. Thanks!
