### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by A-Random-Birb** [mart1nro/joycontrol#39]
Im using vmware 15.5 on an ubuntu VM, and when i run the command to start, im stuck at the "open change grip order" thing, ive already run the commands and stuff from #8, so any ideas?

**Comment by adrianodennanni** [comment]
Same problem, using Ubuntu 19.10 (no vm). I even tried passing the `-r <MAC_ADDRESS>` command, but it gave the `[Errno 111] Connection refused` error.

**Comment by Tenkoni** [comment]
Apparently same as reported in #11 possible VMware limitation.
When testing the script with a VirtualBox VM using Ubuntu 19.10 it works properly after modifying the Bluetooth Class according to #20
