### ISSUE TITLE
Older Raspberry Pi models?

### ISSUE THREAD

**Issue by peterjc** [mart1nro/joycontrol#57]
The main README says:

> *Tested on Ubuntu 19.10 and with Raspberry Pi 4B Raspbian GNU/Linux 10 (buster)*

Presumably a Raspberry Pi 3B might work as that also has bluetooth built in and has reasonable performance? (I have a Raspberry Pi 3 B+ to hand)

Would it be likely to work on an older slower rpi 1 or 2 with a bluetooth dongle? (I have a couple of the original Raspberry Pi B units on hand, and a Broadcom USB bluetooth dongle)

**Comment by mart1nro** [comment]
> Would you like a pull request tweaking the README to say tested on "Raspberry Pi 3B+ and 4B"

Sure.
