### ISSUE TITLE
zl and zr buttons are not functioning properly 

### ISSUE THREAD

**Issue by SomeWhatHappyDuk** [mart1nro/joycontrol#69]
When using `controller_state.button_state.set_button('zl')` it triggers lz as intended but it also triggers zr, after that, I can unpress zl but zr is stuck as constantly triggered. `controller_state.button_state.set_button('zr')` doesn't work at all, I can't get a response from it. The problem is also seen with `await button_push(controller_state, 'zl')`

**Comment by someonewithpc** [comment]
What firmware are you running?

**Comment by SomeWhatHappyDuk** [comment]
I'm using a raspberry pi 3 b+ and raspbian
