### ISSUE TITLE
Is it possible to emulate multiple joycon instances on a single machine at the same time?

### ISSUE THREAD

**Issue by gahoo** [mart1nro/joycontrol#7]
This project is marvlous. But I wonder is it possible to emulate multiple joycon instances on a single machine at the same time?

**Comment by mart1nro** [comment]
The Bluetooth ports for the controller are hard coded and so far as know cannot be changed. It would be possible to use another Bluetooth adapter for a second controller, but it's currently not supported in the code.

**Comment by mart1nro** [comment]
Hey, I added support for multiple Bluetooth adapters now, so multiple controller instances can be emulated.

**Comment by gahoo** [comment]
Wow, that's really nice. I'll give it shot when I got another Bluetooth adapter.

**Comment by mart1nro** [comment]
I'm closing this for now. Feel free to reopen, if you have any more issues.
