### ISSUE TITLE
请问循环语法可以填写无限循环吗？

### ISSUE THREAD

**Issue by luikhh** [mart1nro/joycontrol#84]
【循环】
语法：
FOR 循环次数
...
NEXT

以上语法是否可以设置循环次数为无限？

**Comment by Hill-98** [comment]
你不应该使用中文创建 Issue，因为维护者可能并不熟悉中文。即使维护者熟悉中文，你也应该使用英语，这样可以让更多人了解。

You should not create an issue in Chinese, because the maintainer may not be familiar with Chinese. Even if the maintainer is familiar with Chinese, you should use English so that more people can understand it.
